x-protected-subs: &protected-subs '["67679a5f-45e1-4949-87ac-25df76d12478","sub-2222","sub-3333","sub-4444","sub-5555","sub-6666","sub-7777","sub-8888","sub-9999","sub-0000"]'


x-common-steps: &common-steps
  - uses: actions/checkout@v4

  - name: Azure Login
    uses: azure/login@v2
    with:
      client-id:       ${{ secrets.CLIENTID }}
      tenant-id:       ${{ secrets.TENANT_ID }}
      subscription-id: ${{ github.event.inputs.subscriptionId }}

  - name: Configure SB for Selected Networks + Allow IP
    run: |
      # first add the IP whitelist rule
      az servicebus namespace network-rule-set ip-rule add \
        --resource-group ${{ github.event.inputs.resourceGroup }} \
        --namespace-name ${{ github.event.inputs.serviceBusName }} \
        --ip-rule ip-address=${{ github.event.inputs.ip }}/32 action=Allow

      # then switch the namespace to “Selected networks”
      az servicebus namespace network-rule-set update \
        --resource-group ${{ github.event.inputs.resourceGroup }} \
        --namespace-name ${{ github.event.inputs.serviceBusName }} \
        --default-action Deny

  - name: Queue IP + metadata
    run: |
      az storage queue create \
        --account-name poc2sbwhitelist2 \
        --name sb-whitelist \
        --auth-mode login

      PAYLOAD="${{ github.event.inputs.subscriptionId }}|${{ github.event.inputs.resourceGroup }}|${{ github.event.inputs.serviceBusName }}|${{ github.event.inputs.ip }}/32"
      az storage message put \
        --account-name poc2sbwhitelist2 \
        --queue-name sb-whitelist \
        --content "$PAYLOAD" \
        --auth-mode login