name: Nightly SB Whitelist Cleanup

on:
  workflow_dispatch:

permissions:
  actions: read
  checks: write
  contents: read
  id-token: write
  pull-requests: read
  statuses: read

jobs:
  clean-up:
    environment: env-general
    runs-on: ubuntu-latest
    env:
      AZURE_STORAGE_ACCOUNT: poc2sbwhitelist2 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id:     ${{ secrets.CLIENTID }}
          tenant-id:     ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.subscriptionId }}

      - name: Process all queued IPs
        run: |
          set +e  # Disable exit on error for manual error handling
          
          echo "🔍 Checking queue status..."
          QUEUE_COUNT=$(az storage message peek \
            --account-name $AZURE_STORAGE_ACCOUNT \
            --queue-name sb-whitelist \
            --num-messages 32 \
            --auth-mode login \
            --query 'length(@)' -o tsv)
          
          echo "📊 Found $QUEUE_COUNT messages in queue"
          
          if [ "$QUEUE_COUNT" -eq 0 ]; then
            echo "✅ Queue is empty, nothing to process"
            exit 0
          fi

          PROCESSED_COUNT=0
          ERROR_COUNT=0
          MAX_ITERATIONS=50  # Prevent infinite loop

          for i in $(seq 1 $MAX_ITERATIONS); do
            echo "🔄 Processing batch $i/$MAX_ITERATIONS"
            
            # Get multiple messages for batch processing
            MESSAGES=$(az storage message get \
              --account-name $AZURE_STORAGE_ACCOUNT \
              --queue-name sb-whitelist \
              --num-messages 5 \
              --visibility-timeout 60 \
              --auth-mode login \
              -o json)

            # Exit loop if no messages available
            if [ "$MESSAGES" = "[]" ] || [ "$MESSAGES" = "null" ] || [ -z "$MESSAGES" ]; then
              echo "✅ No more messages in queue"
              break
            fi

            # Process each message in the batch
            echo "$MESSAGES" | jq -c '.[]?' | while read -r msg; do
              if [ -z "$msg" ] || [ "$msg" = "null" ]; then
                continue
              fi

              MSG_ID=$(echo "$msg" | jq -r '.messageId // .id // empty')
              POP_RECEIPT=$(echo "$msg" | jq -r '.popReceipt // empty')
              PAYLOAD=$(echo "$msg" | jq -r '.messageText // .content // empty')
              
              echo "📨 Processing message: $MSG_ID"
              
              # Handle corrupted messages
              if [ -z "$MSG_ID" ] || [ -z "$POP_RECEIPT" ]; then
                echo "⚠️ Message ID or Pop Receipt missing, skipping corrupted message"
                continue
              fi
              
              if [ -z "$PAYLOAD" ]; then
                echo "⚠️ Empty payload detected, deleting message"
                az storage message delete \
                  --account-name $AZURE_STORAGE_ACCOUNT \
                  --queue-name sb-whitelist \
                  --id "$MSG_ID" \
                  --pop-receipt "$POP_RECEIPT" \
                  --auth-mode login 2>/dev/null || echo "Failed to delete empty message"
                ((ERROR_COUNT++))
                continue
              fi

              # Handle masked payloads
              if [[ "$PAYLOAD" == *"***"* ]]; then
                echo "⚠️ Masked payload detected, removing message"
                
                az storage message delete \
                  --account-name $AZURE_STORAGE_ACCOUNT \
                  --queue-name sb-whitelist \
                  --id "$MSG_ID" \
                  --pop-receipt "$POP_RECEIPT" \
                  --auth-mode login 2>/dev/null || echo "Failed to delete masked message"
                
                ((ERROR_COUNT++))
                continue
              fi

              # Parse payload format: subscriptionId|rg|namespace|ip
              # If payload is masked, we cannot recover the original subscription ID
              if [[ "$PAYLOAD" == \*\*\** ]]; then
                echo "❌ Cannot process masked payload - subscription ID is unrecoverable"
                
                az storage message delete \
                  --account-name $AZURE_STORAGE_ACCOUNT \
                  --queue-name sb-whitelist \
                  --id "$MSG_ID" \
                  --pop-receipt "$POP_RECEIPT" \
                  --auth-mode login 2>/dev/null || echo "Failed to delete masked message"
                
                ((ERROR_COUNT++))
                continue
              fi
              
              IFS='|' read -r SUB_ID RG NS IP <<< "$PAYLOAD"
              
              # Validate required fields
              if [ -z "$SUB_ID" ] || [ -z "$RG" ] || [ -z "$NS" ] || [ -z "$IP" ]; then
                echo "❌ Missing required fields, deleting invalid message"
                
                az storage message delete \
                  --account-name $AZURE_STORAGE_ACCOUNT \
                  --queue-name sb-whitelist \
                  --id "$MSG_ID" \
                  --pop-receipt "$POP_RECEIPT" \
                  --auth-mode login 2>/dev/null || echo "Failed to delete invalid message"
                
                ((ERROR_COUNT++))
                continue
              fi

              echo "🎯 Removing $IP from Service Bus '$NS' (RG=$RG)"
              
              # Process IP removal
              SUCCESS=false
              if az account set -s "$SUB_ID" 2>/dev/null; then
                if az servicebus namespace network-rule-set ip-rule remove \
                  --resource-group "$RG" \
                  --namespace-name "$NS" \
                  --ip-rule ip-address="$IP" 2>/dev/null; then
                  echo "✅ IP $IP removed successfully"
                  SUCCESS=true
                  ((PROCESSED_COUNT++))
                else
                  echo "⚠️ IP $IP not found or already removed"
                  SUCCESS=true  # Consider success if IP doesn't exist
                  ((PROCESSED_COUNT++))
                fi
              else
                echo "❌ Failed to access subscription $SUB_ID"
                ((ERROR_COUNT++))
              fi

              # Always attempt to delete message from queue
              az storage message delete \
                --account-name $AZURE_STORAGE_ACCOUNT \
                --queue-name sb-whitelist \
                --id "$MSG_ID" \
                --pop-receipt "$POP_RECEIPT" \
                --auth-mode login 2>/dev/null || echo "⚠️ Failed to delete message from queue"

            done
            
            # Brief pause between iterations
            sleep 2
          done

          echo "🎯 Pipeline completed successfully"