name: Nightly SB Whitelist Cleanup

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  actions: read
  checks: write
  contents: read
  id-token: write
  pull-requests: read
  statuses: read

jobs:
  clean-up:
    runs-on: ubuntu-latest
    env:
      AZURE_STORAGE_ACCOUNT: poc2sbwhitelist2 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id:     ${{ secrets.CLIENTID }}
          tenant-id:     ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.subscriptionId }}

      - name: Process all queued IPs
        run: |
          # 1) peek at up to 5 messages
          echo ">> Queue peek:"
          az storage message peek \
            --account-name $AZURE_STORAGE_ACCOUNT \
            --queue-name sb-whitelist \
            --num-messages 5 \
            --auth-mode login \
            -o table

          # 2) loop until the queue is empty
          while true; do
            # pull one message (invisible 30s)
            MSG_JSON=$(az storage message get \
              --account-name $AZURE_STORAGE_ACCOUNT \
              --queue-name sb-whitelist \
              --num-messages 1 \
              --visibility-timeout 30 \
              --auth-mode login \
              -o json --query '[0]')

            # exit if nothing came back
            if [ "$MSG_JSON" = "null" ]; then
              echo "✅ no more messages, exiting."
              break
            fi

            # extract fields
            MSG_ID=$(echo "$MSG_JSON" | jq -r .messageId)
            POP  =$(echo "$MSG_JSON" | jq -r .popReceipt)
            PAYLOAD=$(echo "$MSG_JSON" | jq -r .messageText)
            IFS='|' read -r SUB_ID RG NS IP <<< "$PAYLOAD"

            echo "→ Removing $IP from Service Bus '$NS' (RG=$RG / Sub=$SUB_ID)…"
            az account set -s "$SUB_ID"
            az servicebus namespace network-rule-set ip-rule remove \
              --resource-group "$RG" \
              --namespace-name "$NS" \
              --ip-rule ip-address="$IP"

            # delete that exact message
            echo "→ Deleting queue message $MSG_ID"
            az storage message delete \
              --account-name $AZURE_STORAGE_ACCOUNT \
              --queue-name sb-whitelist \
              --id "$MSG_ID" \
              --pop-receipt "$POP" \
              --auth-mode login
          done
