name: Nightly SB Whitelist Cleanup

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  actions: read
  checks: write
  contents: read
  id-token: write
  pull-requests: read
  statuses: read

jobs:
  clean-up:
    runs-on: ubuntu-latest
    env:
      AZURE_STORAGE_ACCOUNT: poc2sbwhitelist2 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id:     ${{ secrets.CLIENTID }}
          tenant-id:     ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.subscriptionId }}

      - name: Process all queued IPs (fixed)
        run: |
          # 1) peek at up to 5 messages
          az storage message peek \
            --account-name $AZURE_STORAGE_ACCOUNT \
            --queue-name sb-whitelist \
            --num-messages 5 \
            --auth-mode login \
            -o table

          # 2) loop until the queue is empty
          while true; do
            MSG_JSON=$(az storage message get \
              --account-name $AZURE_STORAGE_ACCOUNT \
              --queue-name sb-whitelist \
              --num-messages 1 \
              --visibility-timeout 30 \
              --auth-mode login \
              -o json --query '[0]')

            [ "$MSG_JSON" = "null" ] && { echo "✅ queue empty, exiting."; break; }

            # extract fields correctly
            MSG_ID=$(echo "$MSG_JSON" | jq -r .messageId)
            POP=$(echo "$MSG_JSON"    | jq -r .popReceipt)    # <— no spaces around '='
            PAYLOAD=$(echo "$MSG_JSON"| jq -r .messageText)
            IFS='|' read -r SUB_ID RG NS IP <<< "$PAYLOAD"

            echo "→ Removing $IP from $NS (RG=$RG / Sub=$SUB_ID)…"
            az account set -s "$SUB_ID"
            az servicebus namespace network-rule-set ip-rule remove \
              --resource-group "$RG" \
              --namespace-name "$NS" \
              --ip-rule ip-address="$IP"

            # delete that exact message
            az storage message delete \
              --account-name $AZURE_STORAGE_ACCOUNT \
              --queue-name sb-whitelist \
              --id "$MSG_ID" \
              --pop-receipt "$POP" \
              --auth-mode login    # <— correct CLI for deleting queue messages :contentReference[oaicite:1]{index=1}
          done
