name: Add IP to SB Whitelist

on:
  workflow_dispatch:
    inputs:
      ip:
        description: 'IP to allow (e.g. 203.0.113.4)'
        required: true
      subscriptionId:
        description: 'Azure Subscription ID'
        required: true
      resourceGroup:
        description: 'Resource Group of your Service Bus'
        required: true
      serviceBusName:
        description: 'Service Bus namespace'
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  add-ip-protected:
    if: contains(fromJson('["67679a5f-45e1-4949-87ac-25df76d12478","sub-B","sub-C"]'), github.event.inputs.subscriptionId)
    runs-on: ubuntu-latest
    environment: env-protected
    steps:
      - name: Add IP & Enqueue (protected)
        uses: ./.github/actions/add-ip
        with:
          ip:              ${{ github.event.inputs.ip }}
          subscriptionId:  ${{ github.event.inputs.subscriptionId }}
          resourceGroup:   ${{ github.event.inputs.resourceGroup }}
          serviceBusName:  ${{ github.event.inputs.serviceBusName }}
          storageAccount:  poc2sbwhitelist2

  add-ip-unprotected:
    if: contains(fromJson('["67679a5f-45e1-4949-87ac-25df76d12478","sub-B","sub-C"]'), github.event.inputs.subscriptionId) == false
    runs-on: ubuntu-latest
    environment: env-general
    steps:
      - name: Add IP & Enqueue (unprotected)
        uses: ./.github/actions/add-ip
        with:
          ip:              ${{ github.event.inputs.ip }}
          subscriptionId:  ${{ github.event.inputs.subscriptionId }}
          resourceGroup:   ${{ github.event.inputs.resourceGroup }}
          serviceBusName:  ${{ github.event.inputs.serviceBusName }}
          storageAccount:  poc2sbwhitelist2