name: Add IP to SB Whitelist

on:
  workflow_dispatch:
    inputs:
      ip:
        description: 'IP to allow (e.g. 203.0.113.4)'
        required: true
      subscriptionId:
        description: 'Azure Subscription ID'
        required: true
      resourceGroup:
        description: 'Resource Group of your Service Bus'
        required: true
      serviceBusName:
        description: 'Service Bus namespace'
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  add-ip-protected:
    if: contains(fromJson(*protected-subs), github.event.inputs.subscriptionId)
    runs-on: ubuntu-latest
    environment: env-protected
    steps: *common-steps

  add-ip-unprotected:
    if: contains(fromJson(*protected-subs), github.event.inputs.subscriptionId) == false
    runs-on: ubuntu-latest
    environment: env-general
    steps: *common-steps