name: Nightly SB Whitelist Cleanup

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  actions: read
  checks: write
  contents: read
  id-token: write
  pull-requests: read
  statuses: read

jobs:
  clean-up:
    runs-on: ubuntu-latest
    env:
      AZURE_STORAGE_ACCOUNT: poc2sbwhitelist2 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id:     ${{ secrets.CLIENTID }}
          tenant-id:     ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.subscriptionId }}

      - name: Process all queued IPs
        run: |
          while true; do
            # 1) Try to get the next messageId; if none, exit
            MSG_ID=$(az storage message get \
              --account-name $AZURE_STORAGE_ACCOUNT \
              --auth-mode login \
              -q '[0].messageId' \
              -o tsv 2>/dev/null)
            if [ -z "$MSG_ID" ]; then
              echo "✅ no more messages, exiting."
              break
            fi

            # 2) Get the popReceipt and the payload text
            POP=$(az storage message get \
              --account-name $AZURE_STORAGE_ACCOUNT \
              --auth-mode login \
              -q '[0].popReceipt' \
              -o tsv)
            PAYLOAD=$(az storage message get \
              --account-name $AZURE_STORAGE_ACCOUNT \
              --auth-mode login \
              -q '[0].messageText' \
              -o tsv)

            # 3) Split payload "subId|rg|namespace|ip"
            IFS='|' read -r SUB_ID RG NS IP <<< "$PAYLOAD"

            echo "→ Removing $IP from Service Bus $NS (RG: $RG / Sub: $SUB_ID)…"
            az account set -s "$SUB_ID"
            az servicebus namespace network-rule-set ip-rule remove \
              --resource-group "$RG" \
              --namespace-name "$NS" \
              --ip-rule ip-address=$IP || true

            # 4) Finally delete that exact message
            az storage message delete \
              --account-name $AZURE_STORAGE_ACCOUNT \
              --auth-mode login \
              -q sb-whitelist \
              --id "$MSG_ID" \
              --pop-receipt "$POP"
          done
