name: Nightly SB Whitelist Cleanup

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  actions: read
  checks: write
  contents: read
  id-token: write
  pull-requests: read
  statuses: read

jobs:
  clean-up:
    runs-on: ubuntu-latest
    env:
      AZURE_STORAGE_ACCOUNT: poc2sbwhitelist2 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id:     ${{ secrets.CLIENTID }}
          tenant-id:     ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.subscriptionId }}

      - name: Process all queued IPs
        run: |
          # loop until the queue is empty
          while true; do
            # fetch one message (invisible for 30s), returning messageId, popReceipt, and messageText
            entry=$(az storage message get \
                      --account-name $AZURE_STORAGE_ACCOUNT \
                      --auth-mode login \
                      -q sb-whitelist \
                      --visibility-timeout 30 \
                      --num-messages 1 \
                      --query '[0].[messageId,popReceipt,messageText]' \
                      -o tsv 2>/dev/null)

            # if no entry, exit loop
            if [ -z "$entry" ]; then
              echo "✅ no more messages, exiting."
              break
            fi

            # show raw entry for debugging
            echo "DEBUG entry: '$entry'"

            # split TSV into three variables
            IFS=$'\t' read -r MSG_ID POP PAYLOAD <<< "$entry"
            echo "DEBUG MSG_ID=$MSG_ID POP=$POP PAYLOAD=$PAYLOAD"

            # split payload (subscriptionId|rg|namespace|ip) on pipe
            IFS='|' read -r SUB_ID RG NS IP <<< "$PAYLOAD"
            echo "DEBUG SUB_ID=$SUB_ID RG=$RG NS=$NS IP=$IP"

            echo "→ Removing $IP from Service Bus $NS (RG: $RG / Sub: $SUB_ID)…"
            az account set -s "$SUB_ID"
            az servicebus namespace network-rule-set ip-rule remove \
              --resource-group "$RG" \
              --namespace-name "$NS" \
              --ip-rule ip-address=$IP || true

            az storage message delete \
              --account-name $AZURE_STORAGE_ACCOUNT \
              --auth-mode login \
              -q sb-whitelist \
              --id "$MSG_ID" \
              --pop-receipt "$POP"
          done
