name: Add IP to SB Whitelist

on:
  workflow_dispatch:
    inputs:
      ip:
        description: 'IP to allow (e.g. 203.0.113.4)'
        required: true
      subscriptionId:
        description: 'Azure Subscription ID'
        required: true
      resourceGroup:
        description: 'Resource Group of your Service Bus'
        required: true
      serviceBusName:
        description: 'Service Bus namespace'
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  add-ip-protected:
    if: contains(
          fromJson('["67679a5f-45e1-4949-87ac-25df76d12478","sub-2222","sub-3333","sub-4444","sub-5555","sub-6666","sub-7777","sub-8888","sub-9999","sub-0000"]'),
          github.event.inputs.subscriptionId
        )
    runs-on: ubuntu-latest
    environment: env-protected
    steps: *common-steps

  add-ip-unprotected:
    if: contains(
          fromJson('["67679a5f-45e1-4949-87ac-25df76d12478","sub-2222","sub-3333","sub-4444","sub-5555","sub-6666","sub-7777","sub-8888","sub-9999","sub-0000"]'),
          github.event.inputs.subscriptionId
        ) == false
    runs-on: ubuntu-latest
    environment: env-general
    steps: *common-steps